---
title: "unit-test"
format: html
editor: visual
---

## Unit testing with the 'testthat' package 

first install necessary packages 
```{r}
#install.packages("testthat")
#install.packages("devtools")
#install.packages("remotes")

library(testthat)
library(devtools)
library(remotes)
```

Write the function to practice unit tests. This function is going to find the mea value of each column and return the lowest and highest mean values. 

We wouuld expect 
- the output to be numeric 
- the output should be a vector of length 2 
- the first value should be smaller than the second value 

```{r}
mean_range <- function(df) {
  # return the mean values of each column 
  col_means <- apply(X = df, MARGIN = 2, FUN = mean, na.rm = TRUE) 
  # find minimum and maximum values 
  col_mean_max <- max(col_means)
  col_mean_min <- min(col_means)
  #return minimum and maximum values in that order
  return(c(col_mean_min, col_mean_max))
}
mean_range(df = mtcars)

```


```{r}
#| include: false # to not include in rendered document
#Test that the output is of length 2
expect_length(mean_range(df = mtcars), 2)

#Test that first output's value is less than the second value 
expect_true(mean_range(mtcars)[1] < mean_range(mtcars)[2])

```

